In [5]:
import sys
import numpy as np

In [2]:
print (sys.version)

3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:32:41) [MSC v.1900 64 bit (AMD64)]


- 가상환경 설치 경로 : conda info --envs

# 파이썬
## 입문

- Module2

    -Part 01. 파이썬 개요 및 기초
    
        01. Basic

In [9]:
A = 4
print(A)

4


In [10]:
print(A+3)

7


In [14]:
print("A=", A)
print("A+3=", A+3)
print("A+3=" + str(A+3))

A= 4
A+3= 7
A+3=7


In [17]:
print("파이썬 배우기")
print("100점")
print("성별 : " + "남자" + "연령 : " + str(27) + "세")
print("성별 : " , "남자", "연령 : ", 27, "세")
print("성별 : %s , 연령 : %d세" % ("남자", 27))
print("성별 : {0} , 나이 : {1}세".format("남자", 27))
print("이름 : %5s \n 중간 : %3.1f점 \t 기말 : %3.2f" % ("이병훈", 27.25, 41.14))
print("이름 : {0:5s} \n 중간 : {1:3.1f}점 \t 기말 : {2:3.2f}".format("이병훈", 27.25, 41.14))

파이썬 배우기
100점
성별 : 남자연령 : 27세
성별 :  남자 연령 :  27 세
성별 : 남자 , 연령 : 27세
성별 : 남자 , 나이 : 27세
이름 :   이병훈 
 중간 : 27.2점 	 기말 : 41.14
이름 : 이병훈   
 중간 : 27.2점 	 기말 : 41.14


- Module2

    -Part 01. 파이썬 개요 및 기초
    
        02. 변수와 자료의 유형

In [28]:
# - 2진수 접두사 : 0b(Binary number)    
# - 8진수 접두사 : 0o(Octal number)
# - 16진수 접두사 : 0x(heXadecimal number)

A = 0b100110
B = 0o107
C = 0x10B
A, B, C

(38, 71, 267)

In [31]:
X = bin(152)
Y = oct(152)
Z = hex(152)
X,Y,Z
# 짧으 문구는 이렇게 : 로 한줄에 쓰기 가능
# X = bin(152): Y = oct(152): Z = hex(152)

('0b10011000', '0o230', '0x98')

In [39]:
# 자료 유형 확인
V = 15.364
W = 15
X = True
Y = 2+3j
Z = "파이썬 이란?"
print("V : {0}\nW : {1}\nX : {2}\nY : {3}\nZ : {4} ".format(type(V), type(W), type(X), type(Y), type(Z)))

V : <class 'float'>
W : <class 'int'>
X : <class 'bool'>
Y : <class 'complex'>
Z : <class 'str'> 


- Module2

    -Part 01. 파이썬 개요 및 기초
    
        03. 연산자

In [32]:
# A=3 -> A+=3 하면 3을 더한값을 Aㅔ 덮어씌움

In [35]:
# += 이처럼 = 연산자를 붙이면 기존 변수값에 연산한 값을 덮어 씌움
a = 3
a += 1
a
# abs 절대값, divmod 몫과나머지, pow 제곱, round(x,y) x를 y번째에서 반올림

4

In [38]:
# == 는 값만을 비교, is 는 값에 할당된 래퍼런스를 비교
# 연산자 우선순위 p.147

In [1]:
# p.142 문자열 연산 함수 표
# S.split(" ")
# S.split(" ", 2) -> 왼쪽부터 두개까지
# S.rsplit(" ", 2)
# S.strip(" ") -> S 양쪽 " " 안에 있는 문자를 제거

- Module2

    -Part 01. 파이썬 개요 및 기초
    
        03. 제어문장 (조건문, 반복문)

In [3]:
a = 75
if (a >= 80):
    print ("합격")
print ("감사합니다.")

감사합니다.


In [4]:
a = 85
if (a >= 80):
    print ("합격")
    print ("축하합니다.")
print ("감사합니다.")

합격
축하합니다.
감사합니다.


In [9]:
a = 78
if (a >= 80):
    print("점수 : {point}".format(point = a))
    # print("점수 : {0}".format(a)) -> 이렇게 간단하게도 표현 가능 {0}, {1} 일시 format(a, b)
    print("합격")
elif (a >= 60):
    print("점수 : {point}".format(point = a))
    print("재시험")
else:
    print("점수 : {point}".format(point = a))
    print("불합격")
print("감사합니다.")

점수 : 78
재시험
감사합니다.


In [10]:
a = 65
res = "합격" if(a>=80) else "재시험" if(a>=60) else "불합격"
print ("점수 : {point}\n{result}".format(point = a, result = res))

점수 : 65
재시험


In [13]:
# 제어문
# for 변수 in [a1, a2, ..., ak]:
# for 변수 in range[a, b, k]:
for i in range(1,10,2):
# for i in range(4): -> 이렇게만 할 경우 순환은 0, 1, 2, 3 까지
    print("{0}번 학생 성적처리...".format(i))
print ("종료합니다.")

1번 학생 성적처리...
3번 학생 성적처리...
5번 학생 성적처리...
7번 학생 성적처리...
9번 학생 성적처리...
종료합니다.


In [19]:
cums = 0
for i in range(11):
# for i in [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]: 과 같은 뜻
    cums+=i
    # print 를 이 부분에 넣을 경우 순환과정을 모두 출력함
print ("1부터 10까지의 합은 {0}입니다.".format(cums))

1부터 10까지의 합은 55입니다.


In [26]:
for i in range(1, 51): # 10열 위치마다 "+" 문자 출력
    if (i%10 == 0):
        print("+", end = "")
        # , end = "" 이걸 안넣을경우 if문에 만족할때마다 + 출력 후 다음줄부터 다시 출력
    else:
        print("-", end = "")

---------+---------+---------+---------+---------+

In [36]:
for i in range(1, 10):
    for j in range(2, 10, 2):
        if (j != 8):
            print ("{0}x{1}={2}".format(i, j, i*j), end = "\t")
        else:
            print ("{0}x{1}={2}".format(i, j, i*j))
            # else 인 j = 8 일 때 print에 end 포인트가 없으므로 다음줄로 줄바꿔 출력 시작

1x2=2	1x4=4	1x6=6	1x8=8
2x2=4	2x4=8	2x6=12	2x8=16
3x2=6	3x4=12	3x6=18	3x8=24
4x2=8	4x4=16	4x6=24	4x8=32
5x2=10	5x4=20	5x6=30	5x8=40
6x2=12	6x4=24	6x6=36	6x8=48
7x2=14	7x4=28	7x6=42	7x8=56
8x2=16	8x4=32	8x6=48	8x8=64
9x2=18	9x4=36	9x6=54	9x8=72


In [39]:
n = 4
cmult = 1
for i in range(1, (n+1)):
    cmult+=i
print("{0}!={1}".format(n, cmult))

4!=11


In [ ]:
# for 변수 in range[a, b, k]:
#    실행문장

# 변수 = a
# while (변수 < b):
#    실행문장
#    변수 += k

# 같은 맥략

In [41]:
fcsum = 0
for i in range(1, 51):
    fcsum+=i
print("1~50까지 합계 {0}".format(fcsum))

wcsum = 0
i = 1
while(i < 51):
    wcsum += i
    i += 1
print("1~50까지 합계 {0}".format(wcsum))

1~50까지 합계 1275
1~50까지 합계 1275


In [37]:
i = 1
while(i < 10):
    j = 2
    while(j <= 8):
        if (j != 8):
            print ("{0}x{1}={2}".format(i, j, i*j), end = "\t")
        else:
            print ("{0}x{1}={2}".format(i, j, i*j))
        j+=2
    i+=1

1x2=2	1x4=4	1x6=6	1x8=8
2x2=4	2x4=8	2x6=12	2x8=16
3x2=6	3x4=12	3x6=18	3x8=24
4x2=8	4x4=16	4x6=24	4x8=32
5x2=10	5x4=20	5x6=30	5x8=40
6x2=12	6x4=24	6x6=36	6x8=48
7x2=14	7x4=28	7x6=42	7x8=56
8x2=16	8x4=32	8x6=48	8x8=64
9x2=18	9x4=36	9x6=54	9x8=72


In [42]:
# 변수 설명문에 i가 없을 경우 i번만큼만 설명문을 돌린다는 뜻
for i in range(3):
    a = int(input("더하고자 하는 첫 번째 값을 입력하세요. (정수) : "))
    b = int(input("더하고자 하는 두 번째 값을 입력하세요. (정수) : "))
    print("{0}+{1}={2}".format(a, b, a+b))
print("계산을 종료합니다.")

# 공통점 : break가 걸린 조건에 만족할 경우 결과값 출력 x
# 다른점 : break가 걸린 조건에 만족할 경우 for문 중단
for i in range(3):
    c = int(input("더하고자 하는 첫 번째 값을 입력하세요. (정수) : "))
    d = int(input("더하고자 하는 두 번째 값을 입력하세요. (정수) : "))
    if (c==0 and d==0):
        break
    print("{0}+{1}={2}".format(c, d, c+d))
print("계산을 종료합니다.")

# 공통점 : continue가 걸린 조건에 만족할 경우 결과값 출력 x
# 다른점 : continue가 걸린 조건에 만족할 경우 해당 조건만 결과출력을 안할뿐 for문은 진행 (continue문 아래쪽만 수행 안됨)
for i in range(3):
    e = int(input("더하고자 하는 첫 번째 값을 입력하세요. (정수) : "))
    f = int(input("더하고자 하는 두 번째 값을 입력하세요. (정수) : "))
    if (e==0 and f==0):
        continue
    print("{0}+{1}={2}".format(e, f, e+f))
print("계산을 종료합니다.")

더하고자 하는 첫 번째 값을 입력하세요. (정수) : 2
더하고자 하는 두 번째 값을 입력하세요. (정수) : 5
2+5=7
더하고자 하는 첫 번째 값을 입력하세요. (정수) : 0
더하고자 하는 두 번째 값을 입력하세요. (정수) : 0
0+0=0
더하고자 하는 첫 번째 값을 입력하세요. (정수) : 3
더하고자 하는 두 번째 값을 입력하세요. (정수) : 7
3+7=10
계산을 종료합니다.
더하고자 하는 첫 번째 값을 입력하세요. (정수) : 2
더하고자 하는 두 번째 값을 입력하세요. (정수) : 5
2+5=7
더하고자 하는 첫 번째 값을 입력하세요. (정수) : 0
더하고자 하는 두 번째 값을 입력하세요. (정수) : 0
계산을 종료합니다.
더하고자 하는 첫 번째 값을 입력하세요. (정수) : 2
더하고자 하는 두 번째 값을 입력하세요. (정수) : 5
2+5=7
더하고자 하는 첫 번째 값을 입력하세요. (정수) : 0
더하고자 하는 두 번째 값을 입력하세요. (정수) : 0
더하고자 하는 첫 번째 값을 입력하세요. (정수) : 3
더하고자 하는 두 번째 값을 입력하세요. (정수) : 7
3+7=10
계산을 종료합니다.


In [46]:
ls = [[3,8,4,6,9,10,8],[3,6,8,3,6,7],[4,3,6,8,0,2,3,2]]
len(ls)

3

In [48]:
avg = []
for i in range(len(ls)):
    avg.append(sum(ls[i])/len(ls[i]))
avg

[6.857142857142857, 5.5, 3.5]

In [52]:
a = {2,3,7,6,4,8,1}
b = {7,2,4}
c = {8,1,3}
NewB = b.update(c)
print("B : {0}\tC : {1}\t BUC : {2}".format(b,c,NewB))

B : {1, 2, 3, 4, 7, 8}	C : {8, 1, 3}	 BUC : None


# 중요!!!!!!!!!!!!!!!!!!!!!!
- Module2

    -Part 01. 파이썬 개요 및 기초
    
        06. 함수(Function) (def)

In [3]:
def print_char(ch = "*", a = 2, b = 10):
    for i in range(a):
        print(ch*b)
    print()

print_char()
print_char("#", 3, 7)
print_char(b=7, ch = "@")

**********
**********

#######
#######
#######

@@@@@@@
@@@@@@@



In [12]:
def calc(a = 2, b = 10, op = "+"):
    if (op == "+"):
        c = a + b
    elif (op == "-"):
        c = a - b
    elif (op == "*"):
        c = a * b
    elif (op == "/"):
        c = a / b if (b != 0) else 0
        # if(b!=0)은 elif의 하위 조건문을 추가한 것. 따라서, a/b를 반환. else일 경우에는 0을 반환
    else:
        print("연산자 기호는 +, -, *, /")
        return
    return c  # 연산자 기호 4가지를 쓰지 않을 경우 print문 출력 후 c값 계산이 안됨으로 None이 다음 줄에 출력
              # 그 말은 곧 print 문 맨 뒤에 end = "" 지정시 None이 다음 줄에 출력되지 않고 붙어서 출력 됨.
print(calc())
print(calc(3, 7, "+"))
print(calc(10, 7, "/"))
print(calc(15, 0, "/"))
print(calc(15, 0, "#"))

12
10
1.4285714285714286
0
연산자 기호는 +, -, *, /
None


In [15]:
def func(*args): # 임의의 인수 / *args는 튜플로 묶어서 처리
    v = args
    print("입력자료 : {0}\n자료의 합계 : {1}\n".format(v, sum(v)))

func(3, 6, 4, 6, 7)
func(25.3, 12.5, 41.3, 63.5, 22.9, 45.8, 77.6)

def func(**kwargs): # 임의의 인수를 키워드 형식으로 삽입 / **kwargs는 사전으로 묶어서 처리
    v = kwargs
    print("입력자료 : {0}\n".format(v))

func(name = "이진호", age = 25, area = "경기")
func(dept = "통계학과", att = 10, mid = 95, final = 87)

입력자료 : (3, 6, 4, 6, 7)
자료의 합계 : 26

입력자료 : (25.3, 12.5, 41.3, 63.5, 22.9, 45.8, 77.6)
자료의 합계 : 288.9

입력자료 : {'name': '이진호', 'age': 25, 'area': '경기'}

입력자료 : {'dept': '통계학과', 'att': 10, 'mid': 95, 'final': 87}



In [2]:
def calc(x = 2, y = 10):
    add = x + y
    dif = x - y
    mul = x * y
    div = x / y
    rem = x + y
    return add, dif, mul, div, rem
    # 콤마로 구분되어 있기 때문에 결과값을 튜플로 출력

z = calc() # 여러개의 반환값을 튜플로 저장
print(z)
v, w, x, y, z = calc() # 여러개의 반환 값을 각각 저장
print(v, w, x, y, z)
v, *w = calc() # *를 붙이면 나머지 모든 변수(리스트)
print(v, w)
v, *w, z = calc() # 양 끝의 데이터 하나씩을 제외한 나머지 모든 변수가 *w (리스트)
print(v, w, z)

(12, -8, 20, 0.2, 12)
12 -8 20 0.2 12
12 [-8, 20, 0.2, 12]
12 [-8, 20, 0.2] 12


In [9]:
a = 15
def func1():
    a = 10
    print("지역변수 a : {0}".format(a))
def func2():
    global a
    a = 10
    print("지역변수 a : {0}".format(a))
func1()
print("전역변수 a : {0}\n".format(a))
func2()
print("전역변수 a : {0}\n".format(a))

지역변수 a : 10
전역변수 a : 15

지역변수 a : 10
전역변수 a : 10



In [14]:
############ 람다합수 ################

# lambda <인수들> : <반환할 식>
print ((lambda x, y : x + y)(2, 3))
# 함수이름 = lambda <인수들> : <반환할 식>
f = lambda x, y : x + y
print(f(7, 9))

5
16


In [21]:
score = [90, 30, 85, 77, 65]
ls = list(enumerate(score)) # 숫자와 쌍이 되는 리스트 (score, n) 으로 인자 입력 시 번호가 n부터 시작
tp = tuple(enumerate(score)) # 숫자와 쌍이 되는 튜플
dic = dict(enumerate(score)) # 카룰 0부터 시작
print("리스트 : {0}\n튜플 : {1}\n사전 : {2}\n".format(ls, tp, dic))

area = ["서울", "경기", "인천"]
dic = dict(enumerate(area, 100)) # 키를 100부터 시작
print(dic)
print("{0}\n".format(dic))

point = [-2, 6, 7, -4, 6, 9]
result = map(abs, point) # point의 각 원소의 절대값 반환 (리스트가 아닌 순수 값들만 순서대로 반환)
print(result) # 이렇게만 출력하면 좌표만 나옴
print(list(result))

score = [9, 3, 7, 5, 6, 8, 4]
result = filter(lambda x:x%2 == 0, score) # score에서 짝수인 원소 반환
# map(lambda x:x%2) 도 가능한데 filter는 조건을 걸어 True인 값만 반환
print(list(result))

리스트 : [(0, 90), (1, 30), (2, 85), (3, 77), (4, 65)]
튜플 : ((0, 90), (1, 30), (2, 85), (3, 77), (4, 65))
사전 : {0: 90, 1: 30, 2: 85, 3: 77, 4: 65}

{100: '서울', 101: '경기', 102: '인천'}
{100: '서울', 101: '경기', 102: '인천'}

[2, 6, 7, 4, 6, 9]
[6, 8, 4]


# 중요!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
- Module2

    -Part 01. 파이썬 개요 및 기초
    
        06. 모듈

In [ ]:
############################### 모듈 #################################
# 내가 def 으로 만든 함수를 저장하기 위해서는 메뉴바 -> File -> Download as -> Python(.py)로 저장하기
# 내가 def 으로 만든 함수는 anaconda 폴더에 test_module에 저장됨
# 따라서 import test_module as tm 으로 불러온 후
# tm.함수이름() 을 통해 언제든지 재사용 가능

In [25]:
import sys
print(sys.builtin_module_names)

('_ast', '_bisect', '_blake2', '_codecs', '_codecs_cn', '_codecs_hk', '_codecs_iso2022', '_codecs_jp', '_codecs_kr', '_codecs_tw', '_collections', '_csv', '_datetime', '_functools', '_heapq', '_imp', '_io', '_json', '_locale', '_lsprof', '_md5', '_multibytecodec', '_opcode', '_operator', '_pickle', '_random', '_sha1', '_sha256', '_sha3', '_sha512', '_signal', '_sre', '_stat', '_string', '_struct', '_symtable', '_thread', '_tracemalloc', '_warnings', '_weakref', '_winapi', 'array', 'atexit', 'audioop', 'binascii', 'builtins', 'cmath', 'errno', 'faulthandler', 'gc', 'itertools', 'marshal', 'math', 'mmap', 'msvcrt', 'nt', 'parser', 'sys', 'time', 'winreg', 'xxsubtype', 'zipimport', 'zlib')


In [26]:
for path in sys.path:
    print(path)

C:\ProgramData\Anaconda3\envs\mypython\python36.zip
C:\ProgramData\Anaconda3\envs\mypython\DLLs
C:\ProgramData\Anaconda3\envs\mypython\lib
C:\ProgramData\Anaconda3\envs\mypython

C:\ProgramData\Anaconda3\envs\mypython\lib\site-packages
C:\ProgramData\Anaconda3\envs\mypython\lib\site-packages\IPython\extensions
C:\Users\Affinity\.ipython


In [28]:
import itertools
# dir(itertools)를 통해서 메소드 목록 보기

ls = [25, 42, 82, 76, 94]
str = "python"
dic = {"서울":"02", "경기":"031", "인천":"032", "세종":"044"}

# 리스트 연결
print(list(itertools.chain(ls, str, dic)))

# 리스트가 아닌 결과값으로만 출력하고 싶을 때
for x in itertools.chain(ls, dic):
    print(x, end = "\t")
print()

[25, 42, 82, 76, 94, 'p', 'y', 't', 'h', 'o', 'n', '서울', '경기', '인천', '세종']
25	42	82	76	94	서울	경기	인천	세종	


In [31]:
for x in itertools.count(50, 5):
# 50부터 5씩 증가한다는 뜻, 디폴트는 0부터 1씩 증가
    if x > 100:
        break
    print(x, end = "\t")
print ("\n")

print(list(zip(itertools.count(1), ["A", "B", "C"])))

50	55	60	65	70	75	80	85	90	95	100	

[(1, 'A'), (2, 'B'), (3, 'C')]


### 중복 및 키워드 관련 모듈

In [51]:
ls = [1,1,2,2,2,2,3,3,3,4,4,4,4,4]
x = itertools.groupby(ls)
# 인자로 ls 뒤에 함수가 없으므로 그냥 같은 것끼리 묶음
# 함수의 결과를 키로 하여 그룹화
for v, k in x:
    # list(k)를 확인하고 싶거나 print()에 list(k)를 활용하고 싶다면 a = list(k)로 할당 저장 후 a로 이용하기
    print("v : {0}\tk : {1}".format(v, list(k)))
print()

ls = ["남자", "여자", "남자", "남자", "남자", "여자", "여자"]
x = itertools.groupby(sorted(ls))
# sorted 안할 시 순서대로 뽑아내기 떄문에 sorted를 해야 원하는 빈도 추출 가능
for v, k in x :
    print("범주 : {0}\t빈도 : {1}".format(v,len(list(k))))

v : 1	k : [1, 1]
v : 2	k : [2, 2, 2, 2]
v : 3	k : [3, 3, 3]
v : 4	k : [4, 4, 4, 4, 4]

범주 : 남자	빈도 : 4
범주 : 여자	빈도 : 3


### 자연어 사전 형태 정리 및 가공 (중요!!!!!!!!)

In [68]:
ls = ["공기", "책상", "소년", "책장", "배움", "백상예술대상", "공집합", "소나기", "책걸상"]
d = {} # 빈 사전 생성
# 사전의 인덱싱 : 사전이름[키값]
for word in sorted(ls) :
    if word[0] in d: # 단어 첫 글자가 d에 key로 있다면
        d[word[0]].append(word) # d의 word[0] 키에 word를 값으로 추가
    else: # 단어 첫 글자가 d에 key로 없다면
        d[word[0]] = [] # 우선 값 없이 키만 저장한 후
        d[word[0]].append(word) # 그 키에 데이터 값을 추가

for k in d.keys() : # k는 d라는 사전의 키 이름만을 뽑기 위한 for문
    d[k].sort()

for k, v in d.items() : # 사전이름.items()는 key와 값을 튜플 형태로 반환하는 함수
    print(k, v)

공 ['공기', '공집합']
배 ['배움']
백 ['백상예술대상']
소 ['소나기', '소년']
책 ['책걸상', '책상', '책장']


In [70]:
for k, group in itertools.groupby(sorted(ls), lambda w : w[0]): # groupby(x, f) : f 결과를 키로 사용하여 사전의 형태로 값을 반환
    print(k, list(group))

공 ['공기', '공집합']
배 ['배움']
백 ['백상예술대상']
소 ['소나기', '소년']
책 ['책걸상', '책상', '책장']


In [72]:
#### input을 활용한 출력 ( 숫자 입력시에는  int(input())을 적용해야함)
name = input("이름을 입력해 주세요 : ")
point = int(input("점수를 입력해 주세요 : "))
print("{0}님의 점수는 {1}입니다.".format(name, point))

이름을 입력해 주세요 : 이병진
점수를 입력해 주세요 : 85
이병진님의 점수는 85입니다.


In [79]:
import calendar
print(calendar.calendar(2019))

                                  2019

      January                   February                   March
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
    1  2  3  4  5  6                   1  2  3                   1  2  3
 7  8  9 10 11 12 13       4  5  6  7  8  9 10       4  5  6  7  8  9 10
14 15 16 17 18 19 20      11 12 13 14 15 16 17      11 12 13 14 15 16 17
21 22 23 24 25 26 27      18 19 20 21 22 23 24      18 19 20 21 22 23 24
28 29 30 31               25 26 27 28               25 26 27 28 29 30 31

       April                      May                       June
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
 1  2  3  4  5  6  7             1  2  3  4  5                      1  2
 8  9 10 11 12 13 14       6  7  8  9 10 11 12       3  4  5  6  7  8  9
15 16 17 18 19 20 21      13 14 15 16 17 18 19      10 11 12 13 14 15 16
22 23 24 25 26 27 28      20 21 22 23 24 25 26      17 18 19 20 21 22 23
29 30                     

- Module2

    -Part 01. 파이썬 개요 및 기초
    
        07. 파일 읽기와 쓰기 p.219 ~

In [80]:
# open으로 파일을 읽었다면 항상 작업 완료 후 close를 적용해주자!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
fobj = open("C:/Users/Affinity/Desktop/study/Python_Data/ch01_data/data_space.txt")
robj = fobj.read() # read(n)으로 지정하면 n개의 문자열만 저장(줄바꿈 문자 포함)
print(robj)
data = robj.split()
print(data)
fobj.close()

height weight
174.10 71.85
171.17 65.46
175.73 72.29
178.83 72.49
178.60 73.38
180.20 75.40
168.45 66.62
174.30 70.84
178.29 72.12
171.74 69.66

['height', 'weight', '174.10', '71.85', '171.17', '65.46', '175.73', '72.29', '178.83', '72.49', '178.60', '73.38', '180.20', '75.40', '168.45', '66.62', '174.30', '70.84', '178.29', '72.12', '171.74', '69.66']


In [100]:
# Height와 Weight 데이터 따로 저장하기
fobj = open("C:/Users/Affinity/Desktop/study/Python_Data/ch01_data/data_space.txt")
robj = fobj.read()
x = robj.split()
Height = []
Weight = []
for i in range(2, len(x), 2) :
    Height.append(x[i]) # char이 아닌 float형으로 저장하려면 이 부분에서 float(x[i])로 지정해야함
    Weight.append(x[i+1])
Height, Weight

(['174.10',
  '171.17',
  '175.73',
  '178.83',
  '178.60',
  '180.20',
  '168.45',
  '174.30',
  '178.29',
  '171.74'],
 ['71.85',
  '65.46',
  '72.29',
  '72.49',
  '73.38',
  '75.40',
  '66.62',
  '70.84',
  '72.12',
  '69.66'])

In [84]:
fobj = open("C:/Users/Affinity/Desktop/study/Python_Data/ch01_data/data_space.txt")
robj = fobj.readline() # 줄 끝에 있는 \n 까지 읽어옴
print("1 : {0}".format(robj))
robj = fobj.readline().strip() # strip으로 양끝 공백을 제거하거나 [:-1]로 \n을 빼고 읽음
print("2 : {0}".format(robj))
robj = fobj.readline(6) # 한 줄에서 6글자
print("3 : {0}".format(robj))
robj = fobj.readline(12) # 앞에서 종료한 위치로부터 12글자 ("\n 문자에서 종료")
print("4 : {0}".format(robj))
fobj.close()

1 : height weight

2 : 174.10 71.85
3 : 171.17
4 :  65.46



In [7]:
fobj = open("C:/Users/Affinity/Desktop/study/Python_Data/ch01_data/data_space.txt")
robj = fobj.readline()
while robj : # 빈 문자열이 있으면 종료
    print(robj, end = "") # end 포인트 안잡아주면 \n이 적용되어 한줄씩 띄어 출력
    robj = fobj.readline() # 마지막 줄 까지 읽으면 빈 문자열 읽기
fobj.close()

height weight
174.10 71.85
171.17 65.46
175.73 72.29
178.83 72.49
178.60 73.38
180.20 75.40
168.45 66.62
174.30 70.84
178.29 72.12
171.74 69.66


In [8]:
fobj = open("C:/Users/Affinity/Desktop/study/Python_Data/ch01_data/NewFile.txt", 'w')
# 'w'는 기존의 내용 지우고 덮어쓰기, 'a'는 기존의 내용 보존하고 이어쓰기
robj = fobj.write("파이썬 파일 쓰기")
fobj.close()

In [9]:
rf = open("C:/Users/Affinity/Desktop/study/Python_Data/ch01_data/score.txt")
wf = open("C:/Users/Affinity/Desktop/study/Python_Data/ch01_data/stat.txt", 'w')
point = []
for x in rf :
    point.append(float(x))
    wf.write(x)
wf.write("\n")
wf.write(str(sum(point) / len(point)))
wf.close()
rf.close()

# 중요!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
- Module2

    -Part 02. 빅데이터 전처리 및 시각화
    
        01. NumPy

In [2]:
import numpy as np
data = np.random.randn(2, 3)
data, data.shape, data.dtype

(array([[-0.30343877,  1.03341586, -0.36612954],
        [-0.12818703,  0.09681566, -0.82240921]]), (2, 3), dtype('float64'))

##### ndarray 메소드 p.234

In [12]:
ls1 = [3, 2, 5, 6, 3]
ls2 = [9, 3, 5, 4, 1]

vec_x = np.array(ls1) # 벡터
mat_a = np.array([ls1, ls2]) # 행렬

print(vec_x, vec_x.shape, vec_x.ndim, vec_x.dtype)
print(mat_a, mat_a.shape, mat_a.ndim, mat_a.dtype)

data3 = np.asarray(vec_x) # 기존의 ndarray는 객체를 공유
print(data3, id(vec_x), id(data3)) # 행렬을 행렬로 변환 (ID가 같음)
data3 = np.asarray(ls1) # 새로운 ndarray 생성
print(data3, id(vec_x), id(data3)) # 벡터를 행렬로 변환 (ID가 다름)

[3 2 5 6 3] (5,) 1 int32
[[3 2 5 6 3]
 [9 3 5 4 1]] (2, 5) 2 int32
[3 2 5 6 3] 2284606915328 2284606915328
[3 2 5 6 3] 2284606915328 2284606900224


In [11]:
print("range : {0}".format(np.arange(3, 10, 3))) # range와 유사
print("zeros(n) : {0}".format(np.zeros(4))) # 지정한 크기의 ndarray(초기값 0)
print("zeros((r,c)) : \n{0}".format(np.zeros((3,2)))) # 괄호 2개 넣으면 2차원 행렬을 생성
print("zeros_like(obj) : {0}".format(np.zeros_like(ls1))) # 기존 개체를 0으로 초기화
print("zeros_like(ndarray) : \n{0}".format(np.zeros_like(data2)))
print("ones((r,c)) : \n{0}".format(np.ones((3,2))))
print("eye(n) : \n{0}".format(np.eye(3))) # 단위 행렬

range : [3 6 9]
zeros(n) : [0. 0. 0. 0.]
zeros((r,c)) : 
[[0. 0.]
 [0. 0.]
 [0. 0.]]
zeros_like(obj) : [0 0 0 0 0]
zeros_like(ndarray) : 
[[0 0 0 0 0]
 [0 0 0 0 0]]
ones((r,c)) : 
[[1. 1.]
 [1. 1.]
 [1. 1.]]
eye(n) : 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [13]:
ls = [2, 6, 8, 7, 5, 6]
x = np.array([2, 6, 8, 7, 5, 6])

ls[2:4] = [6] # 슬라이싱으로 리스트 원소 변경 (변경값은 []로 감싸주어야함)
print("ls[2:4] = [6] : {0}".format(ls))
# ls[2]와 ls[3]이 [6] 하나의 값으로 변경됨
x[2:4] = 6 # 슬라이싱으로 배열 원소 변경
print("x[2:4] = 6 : {0}".format(x))
# x[2]와 x[3]이 각각 6으로 변경됨

ls[2:4] = [6] : [2, 6, 6, 5, 6]
x[2:4] = 6 : [2 6 6 6 5 6]


In [15]:
# 1차원과 2차원 배열의 bool
name = np.array(["남자", "여자", "남자", "남자", "남자", "여자"])
score = np.array([[10, 20, 30, 40], [8, 15, 24, 31], [5, 11, 20, 25], 
                 [6, 9, 16, 17], [10, 17, 21, 27], [9, 13, 27, 31]])
name_bool = name=="여자"
print("name\n{0}".format(name))
print("score\n{0}".format(score))
# [0, 0, ..., 1] 원소마다 부울이 적용됨

female = score[name_bool]
male = score[~name_bool]
# & : and, | : or, ^ : and or, ~ : not
print("female\n{0}".format(female))
print("male\n{0}".format(male))

name
['남자' '여자' '남자' '남자' '남자' '여자']
score
[[10 20 30 40]
 [ 8 15 24 31]
 [ 5 11 20 25]
 [ 6  9 16 17]
 [10 17 21 27]
 [ 9 13 27 31]]
female
[[ 8 15 24 31]
 [ 9 13 27 31]]
male
[[10 20 30 40]
 [ 5 11 20 25]
 [ 6  9 16 17]
 [10 17 21 27]]


In [16]:
cls = np.array(["1학년", "2학년", "3학년", "1학년", "3학년", "2학년"])
score = np.array([[10, 20, 30, 40], [8, 15, 24, 31], [5, 11, 20, 25], 
                 [6, 9, 16, 17], [10, 17, 21, 27], [9, 13, 27, 31]])
print("name\n{0}".format(cls))
print("score\n{0}".format(score))
print("score(1학년 또는 2학년)\n{0}".format(score[(cls == "1학년") | (cls == "2학년")]))
# array[(조건)]의 형태로 지정해주어야함
# 또는 array[array>=n]의 형태로도 가능

name
['1학년' '2학년' '3학년' '1학년' '3학년' '2학년']
score
[[10 20 30 40]
 [ 8 15 24 31]
 [ 5 11 20 25]
 [ 6  9 16 17]
 [10 17 21 27]
 [ 9 13 27 31]]
score(1학년 또는 2학년)
[[10 20 30 40]
 [ 8 15 24 31]
 [ 6  9 16 17]
 [ 9 13 27 31]]


In [17]:
arr = np.arange(24).reshape(2, 4, 3)
arr1 = arr.transpose(2, 0, 1)
# 축 인덱스로 지정 (3x2x4) / 열을 층, 층을 행, 행을 열로 지정
print("arr\n{0}\narr1\n{1}".format(arr, arr1))

arr
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]
arr1
[[[ 0  3  6  9]
  [12 15 18 21]]

 [[ 1  4  7 10]
  [13 16 19 22]]

 [[ 2  5  8 11]
  [14 17 20 23]]]


In [18]:
arr2 = arr.swapaxes(2, 0)
# swapaxes 함수는 인자를 2개만 받는다
# 층과 열을 swap한다는 뜻
# 인자로 들어가지 않은 행은 고정
print("arr2\n{0}".format(arr2))

arr2
[[[ 0 12]
  [ 3 15]
  [ 6 18]
  [ 9 21]]

 [[ 1 13]
  [ 4 16]
  [ 7 19]
  [10 22]]

 [[ 2 14]
  [ 5 17]
  [ 8 20]
  [11 23]]]


In [19]:
x = np.array([2.5, 5.6, 8.1, 3.9, 5.7])
y = np.array([2, 6, -3, 5, -5])
A = np.array([x, y])
print("sqrt(x) = {0}".format(np.sqrt(x))) # 제곱근
print("rint(exp(x)) = {0}".format(np.rint(np.exp(x)))) # 소수자리 반올림 -> 정수가 됨
print("log(x) = {0}".format(np.log(x))) # log2, log10 처럼 밑이 없으면 자연로그
print("abs(y) = {0}".format(np.abs(y)))
print("sign(y) = {0}".format(np.sign(y))) # 부호 출력(양수:1, 0:0, 음수:-1)

r, q = np.modf(A) # 1로 나눈 목과 값을 배열로 출력
#목행 따로 나머지 행 따로
print("modf(A)\n{0}\n{1}".format(r, q))

sqrt(x) = [1.58113883 2.36643191 2.84604989 1.97484177 2.38746728]
rint(exp(x)) = [  12.  270. 3294.   49.  299.]
log(x) = [0.91629073 1.7227666  2.09186406 1.36097655 1.74046617]
abs(y) = [2 6 3 5 5]
sign(y) = [ 1  1 -1  1 -1]
modf(A)
[[ 0.5  0.6  0.1  0.9  0.7]
 [ 0.   0.  -0.   0.  -0. ]]
[[ 2.  5.  8.  3.  5.]
 [ 2.  6. -3.  5. -5.]]


In [20]:
A = (10+3*np.random.randn(12)).reshape(4, 3)
B = np.arange(1, 13).reshape(4, 3)
print("minimum(A,B)\n{0}".format(np.minimum(A,B)))
print("A>=B\n{0}".format(np.greater_equal(A,B)))
AL = np.greater_equal(A,8)
AU = np.less(A,10)
print("8<=A<10\n{0}".format(np.logical_and(AL, AU)))

minimum(A,B)
[[1.         2.         3.        ]
 [4.         5.         6.        ]
 [6.40770962 8.         7.19370544]
 [9.25636843 9.29073505 5.28218569]]
A>=B
[[ True  True  True]
 [ True  True  True]
 [False  True False]
 [False False False]]
8<=A<10
[[False False False]
 [ True False False]
 [False False False]
 [ True  True False]]


##### 배열연산 조건절 (np.where)

In [22]:
xarr = np.array([2.5, 5.6, 8.1, 3.9, 5.7])
yarr = np.array([2, 6, -3, 4, -5])
zarr = np.array(["서울", "경기", "서울", "인천", "경기"])
result = [(x if z == "서울" else y) for x, y, z in zip(xarr, yarr, zarr)]
# z가 '서울'이면 x 그렇지 않으면 y값을 출력
# zip으로 묶는이유는 (2.5, 2, "서울"), (5.6, 6, "경기") 이런식으로 만들어 함수적용하기 위해
# 이렇듯 리스트를 이용한 방법은 1차원 배열에서만 가능 -> 다차원 불가능
print(result)

[2.5, 6, 8.1, 4, -5]


In [23]:
xarr = np.array([2.5, 5.6, 8.1, 3.9, 5.7])
yarr = np.array([2, 6, -3, 4, -5])
zarr = np.array(["서울", "경기", "서울", "인천", "경기"])
result = np.where(zarr == '서울', xarr, yarr)
# x if 조건 else y와 같은 삼항 연산자의 벡터화된 버전 (일차원 다차원 모두 가능)
# np.where(조건, x, y)
print(result)

[ 2.5  6.   8.1  4.  -5. ]


In [24]:
arr1 = (10+5*np.random.randn(12)).reshape(4, 3)
arr2 = (10+5*np.random.randn(12)).reshape(4, 3)
result = np.where(arr1 >= 10, arr1, np.where(arr2 >= 10, arr2, 0))
print("arr1\n{0}\narr2\n{1}\nresult\n{2}".format(arr1, arr2, result))

arr1
[[ 6.98958697 13.33251012  6.16443695]
 [ 3.09103761  3.85792427 22.5723202 ]
 [ 1.20052637 11.88229518  5.70159473]
 [14.96249731 11.41062885 14.81245052]]
arr2
[[ 6.89531182 10.24488729 16.57469517]
 [10.35785877 15.79171389  1.87926755]
 [12.31027846  7.3519881  12.52515881]
 [ 6.93417412 16.08758183  6.4184121 ]]
result
[[ 0.         13.33251012 16.57469517]
 [10.35785877 15.79171389 22.5723202 ]
 [12.31027846 11.88229518 12.52515881]
 [14.96249731 11.41062885 14.81245052]]


##### 통계 메소드

In [25]:
xarr = np.array([2.5, 5.6, 8.1, 3.9, 5.7])
print("x.sum() = {0}\tsum(x) = {1}".format(xarr.sum(), np.sum(xarr))) # 합계
print("x.mean() = {0}\tmean(x) = {1}".format(xarr.mean(), np.mean(xarr))) # 평균
print("x.std() = {0}\tstd(x) = {1}".format(xarr.std(ddof = 0), np.std(xarr, ddof = 0))) # 표준편차 (n)
print("x.std() = {0}\tstd(x) = {1}".format(xarr.std(ddof = 1), np.std(xarr, ddof = 1))) # 표준편차 (n-1)
print("x.var() = {0}\tvar(x) = {1}".format(xarr.var(ddof = 1), np.var(xarr, ddof = 1))) # 분산 (n-1)
print("x.min() = {0}\tmin(x) = {1}".format(xarr.min(), np.min(xarr))) # 최소값
print("x.max() = {0}\tmax(x) = {1}".format(xarr.max(), np.max(xarr))) # 최대값
print("x.argmin() = {0}\targmin(x) = {1}".format(xarr.argmin(), np.argmin(xarr))) # 최소값 인덱스
print("x.argamx() = {0}\targmax(x) = {1}".format(xarr.argmax(), np.argmax(xarr))) # 최대값 인덱스
print("x.cumsum() = {0}\tcumsum(x) = {1}".format(xarr.cumsum(), np.cumsum(xarr))) # 누적합
# 열 누적합 -> 밑으로 가면서 더함 / 행 누적합 -> 오른쪽으로 가면서 더함
print("x.cumprod() = {0}\tcumprod(x) = {1}".format(xarr.cumprod(), np.cumprod(xarr))) # 누적곱

x.sum() = 25.799999999999997	sum(x) = 25.799999999999997
x.mean() = 5.159999999999999	mean(x) = 5.159999999999999
x.std() = 1.8863721796082553	std(x) = 1.8863721796082553
x.std() = 2.109028212234251	std(x) = 2.109028212234251
x.var() = 4.448	var(x) = 4.448
x.min() = 2.5	min(x) = 2.5
x.max() = 8.1	max(x) = 8.1
x.argmin() = 0	argmin(x) = 0
x.argamx() = 2	argmax(x) = 2
x.cumsum() = [ 2.5  8.1 16.2 20.1 25.8]	cumsum(x) = [ 2.5  8.1 16.2 20.1 25.8]
x.cumprod() = [2.500000e+00 1.400000e+01 1.134000e+02 4.422600e+02 2.520882e+03]	cumprod(x) = [2.500000e+00 1.400000e+01 1.134000e+02 4.422600e+02 2.520882e+03]


In [28]:
xarr = np.array([[2.5, 5.6, 8.1], [3.9, 5.7, 2.9], [6.1, 9.7, 5.4], [1.4, 8.3, 4.2]])
print("xrr\n{0}".format(xarr))
print("전체평균 : {0}".format(xarr.mean()))
print("열 평균\n{0}\n행 평균\n{1}".format(xarr.mean(axis = 0), xarr.mean(axis = 1)))
print("열 편차\n{0}\n행 편차\n{1}".format(xarr.std(axis = 0, ddof = 1), xarr.std(axis = 1, ddof = 1)))
# 배열 array에서는 axis=0 -> 열 / axis=1 -> 행

xrr
[[2.5 5.6 8.1]
 [3.9 5.7 2.9]
 [6.1 9.7 5.4]
 [1.4 8.3 4.2]]
전체평균 : 5.316666666666666
열 평균
[3.475 7.325 5.15 ]
행 평균
[5.4        4.16666667 7.06666667 4.63333333]
열 편차
[2.02710796 2.01721756 2.21585198]
행 편차
[2.80535203 1.41891978 2.307235   3.47035061]


    배열 데이터 처리 (True값 갯수 찾기)

In [30]:
arr = (10+5*np.random.randn(12)).reshape(4,3)
print("True의 개수 : {0}".format((arr>=10).sum()))
# 논리값 False = 0, True = 1
print("True의 비율 : {0}".format((arr>=10).mean()))
arr = np.array([True, False, True, True, False])
print("True의 비율 : {0}".format(arr.all())) # 모두 True이면 True
print("True의 비율 : {0}".format(arr.any())) # 모두 False이면 False

True의 개수 : 8
True의 비율 : 0.6666666666666666
True의 비율 : False
True의 비율 : True


In [31]:
# for문 안돌리고 list 중복 원소만 추출하기 p.255
# 교집합, 합집합, 차집합, xor, unique

        배열 입출력 p.256
        텍스트 파일 불러오기, 저장하기 p.257

In [8]:
steel_data = np.loadtxt("C:/Users/Affinity/Desktop/study/Python_Data/ch02_data/steel.txt",
                       skiprows = 5, delimiter = "\t" , usecols=(0,2), unpack = True)
# 줄 생략 = skiprows, 구분좌 = delimiter, 불러올 열 지정 = usecols, 전치시키기 = unpack
# 아스키코드나 utf-8이어야 함
print("steel_data\n{0}".format(steel_data))

steel_data
[[ 81.4 122.2 101.7 175.6 150.3  64.8  92.1 113.8]
 [ 57.   61.   60.   62.   61.   54.   58.   61. ]]


##### 선형대수학 메소드 p.258

#### 중요!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    - linarg.svd(특이값분해) 메소드로 정방이 아닌 행렬의 역행렬을 구할 수 있다.
    - psuedo inverse 를 통해 SSE를 산출 할 수 있다.

In [15]:
A = np.array([[1, 3, 5, 7], [5, 3, 4, 7]])
B = np.array([[1, 3], [5, 7], [5, 3], [4, 7]])
C = np.array([[4, 9, 1, 3], [7, 5, 2, 7], [5, 3, 4, 3], [1, 4, 7, 9]])
print("A\n{0}\nB\n{1}\nC\n{2}".format(A, B, C))
print("AB\n{0}".format(np.dot(A, B))) # 행렬의 곱 (내적)
print("diag(C)\n{0}".format(np.diag(C))) # 행렬 C의 대각 원소
print("diag(A[1])\n{0}".format(np.diag(A[1]))) # 행렬 A의 1행을 대각 원소로 하는 행렬
# diag()는 2가지 기능을 보유함 -> n x n 배열의 대각원소 반환 / 1차원 배열을 대각 원소로 하는 n x n 배열 반환
print("trace(A)\n{0}".format(np.trace(A))) # 행렬 A의 대각 원소 합
print("det(C)\n{0}".format(np.linalg.det(C))) # 행렬 C의 행렬식
print("inv(C)\n{0}".format(np.linalg.inv(C))) # 행렬 C의 역행렬
print("Cinv(C)\n{0}".format(np.rint(np.dot(C, np.linalg.inv(C))))) # Cinc(C)
# linalg.inv() -> 인자의 역행렬 반환 / np.rint() -> 소수점자리에서 반올림
eig_v, eig_vec = np.linalg.eig(C)
print("고유값\n{0}\n고유벡터\n{1}".format(eig_v, eig_vec)) # 행렬 C의 고유값과 고유벡터

A
[[1 3 5 7]
 [5 3 4 7]]
B
[[1 3]
 [5 7]
 [5 3]
 [4 7]]
C
[[4 9 1 3]
 [7 5 2 7]
 [5 3 4 3]
 [1 4 7 9]]
AB
[[69 88]
 [68 97]]
diag(C)
[4 5 4 9]
diag(A[1])
[[5 0 0 0]
 [0 3 0 0]
 [0 0 4 0]
 [0 0 0 7]]
trace(A)
4
det(C)
-1549.999999999999
inv(C)
[[-0.0516129   0.08709677  0.13870968 -0.09677419]
 [ 0.15354839 -0.0716129  -0.02516129  0.01290323]
 [-0.00903226 -0.17225806  0.23677419  0.05806452]
 [-0.05548387  0.15612903 -0.1883871   0.07096774]]
Cinv(C)
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [-0.  0.  1. -0.]
 [-0.  0. -0.  1.]]
고유값
[18.95137965+0.j         -4.18786225+0.j          3.6182413 +2.53735307j
  3.6182413 -2.53735307j]
고유벡터
[[ 0.47831238+0.j          0.64722509+0.j         -0.47647899-0.11511806j
  -0.47647899+0.11511806j]
 [ 0.56955835+0.j         -0.65592208+0.j         -0.12915359-0.16898385j
  -0.12915359+0.16898385j]
 [ 0.38401956+0.j         -0.26047634+0.j         -0.37310913+0.35580654j
  -0.37310913-0.35580654j]
 [ 0.54712843+0.j          0.2881284 +0.j          0.669

In [16]:
# p.260 같이보기
y = np.array([2, 4, 6, 3, 7, 1]) # 종속변수
x = np.array([[1, 2, 3, 7], [1, 5, 7, 6], [1, 6, 7, 3],[1, 7, 3, 4], [1, 8, 4, 3], [1, 3, 2, 5]]) #독립변수
print("x\n{0}\ny\n{1}".format(x, y))
print("최소제곱추정량\n{0}".format(np.linalg.lstsq(x,y)))

x
[[1 2 3 7]
 [1 5 7 6]
 [1 6 7 3]
 [1 7 3 4]
 [1 8 4 3]
 [1 3 2 5]]
y
[2 4 6 3 7 1]
최소제곱추정량
(array([ 1.1991453 ,  0.44871795,  0.45854701, -0.35811966]), array([5.52948718]), 4, array([20.5718539 ,  5.90695272,  3.85261955,  0.25309904]))


C:\ProgramData\Anaconda3\envs\mypython\lib\site-packages\ipykernel_launcher.py:4: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  after removing the cwd from sys.path.


In [22]:
xt = x.T
xpx = np.dot(xt, x)
np.dot(np.dot(np.linalg.inv(xpx), xt), y) # 최소제곱추정량

array([ 1.1991453 ,  0.44871795,  0.45854701, -0.35811966])

In [7]:
steel = np.loadtxt("C:/Users/Affinity/Desktop/study/Python_Data/ch02_data/steel.txt",
                       skiprows = 5, delimiter = "\t")
y = steel[:,0].copy()
X = steel.copy()
X[:,0] = 1
print(steel, x, y)
# 작성하다맘

[[ 81.4 195.   57. ]
 [122.2 179.   61. ]
 [101.7 205.   60. ]
 [175.6 204.   62. ]
 [150.3 201.   61. ]
 [ 64.8 184.   54. ]
 [ 92.1 210.   58. ]
 [113.8 209.   61. ]] [[  1. 195.  57.]
 [  1. 179.  61.]
 [  1. 205.  60.]
 [  1. 204.  62.]
 [  1. 201.  61.]
 [  1. 184.  54.]
 [  1. 210.  58.]
 [  1. 209.  61.]] [ 81.4 122.2 101.7 175.6 150.3  64.8  92.1 113.8]


##### 난수 생성 메소드 p.261
    - ex)난수변수를 추가해 난수 값이 n이상인 부분은 실험용, 이하는 검증용으로 사용함

    - np.random.seed
    - np.random.randint : 균일 분포의 정수 난수 1개 생성
    - np.random.rand : 0부터 1사이의 균일 분포에서 난수 matrix array 생성
    - np.random.randn : 가우시안 표준 정규 분포에서 난수 matrix array 생성
    - np.random.shuffle : 기존의 데이터의 순서 바꾸기
    - np.random.choice : 기존의 데이터에서 sampling

In [12]:
np.random.seed(123456789) # 시드값 고정
norm_sample1 = np.random.randn(20) # N(0,1)
norm_sample2 = np.random.normal(size = 20) # N(0,1)
norm_sample3 = np.random.normal(loc = 10, scale = 2, size=(5,4)) # N(10,4)
print("randn\n{0}".format(norm_sample1))
print("normal(20)\n{0}\nnormal(size=(4,5))\n{1}".format(norm_sample2, norm_sample3))

randn
[ 2.212902    2.1283978   1.8417114   0.08238248  0.85896368 -0.82601643
  1.15727052  1.37591514  0.94302846  0.8478706   0.52969142 -0.56940469
  0.83180456  0.23359639 -0.84767033 -1.67666183  0.03332262  0.38044469
 -0.80288458 -0.83511902]
normal(20)
[-1.06883444  0.18993115 -0.05553701  1.06244261  0.57964676 -0.32022184
 -0.26975584  0.32321392  1.3743362  -0.20494313  0.27613222  0.16255978
 -0.43567345  0.09642087 -1.88685108  0.58084648  3.28724603  0.20887862
 -0.5197155   2.02425663]
normal(size=(4,5))
[[10.63925044  8.9154161   9.0673001  10.73897138]
 [ 9.34684305 12.27415815  6.53727444  7.49462658]
 [ 9.96194907 11.70244161  9.13842665  9.7386879 ]
 [ 8.05728605  6.56209521  8.58631907  8.72643932]
 [10.24602117 11.38838356 12.11191519 10.76492175]]


In [16]:
x = np.array([[1,3,6], [1,5,4], [1,3,6],[1,4,6],[1,7,3],[1,8,4],[1,9,7],[1,3,6],[1,5,2],[1,7,6]])
beta = np.array([10,-2.5,5.5])
np.random.seed(1234) # seed값을 지정해줌으로써 lstsq 메소드 실행했을 때 값이 동일하게 출력
e = np.random.normal(loc = 0, scale = 2, size = 10)
y = np.dot(x,beta) + e
print(x, beta, y)
np.linalg.lstsq(x, y) # 직접 입력한 beta값과 비교하기

[[1 3 6]
 [1 5 4]
 [1 3 6]
 [1 4 6]
 [1 7 3]
 [1 8 4]
 [1 9 7]
 [1 3 6]
 [1 5 2]
 [1 7 6]] [10.  -2.5  5.5] [36.44287033 17.11804861 38.36541394 32.37469621  7.55882253 13.77432588
 27.71917683 34.22695299  8.53139274 21.01463009]


C:\ProgramData\Anaconda3\envs\mypython\lib\site-packages\ipykernel_launcher.py:7: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  import sys


(array([ 9.14457203, -2.5512041 ,  5.66891263]),
 array([43.38911395]),
 3,
 array([24.13008397,  6.1037028 ,  0.6956002 ]))